### ISSUE TITLE
Unable to upload captured data

### ISSUE THREAD

**Issue by kill0rz** [wiglenet/wigle-wifi-wardriving#122]
Hi,

since last update on play store there is no upload to wigle.net possible anymore.
Everytime I hit the upload button, the error appears that the file to upload is empty.

Is the captured data lost?

**Comment by bobzilladev** [comment]
I would guess the database used to be on the sdcard and you said "no" to allowing the app to talk to the sdcard. Or the database used to be on internal storage and you said "yes" to allowing the app to talk to the sdcard. Either way the database would start out fresh, but the pointer to the last updated record would no longer make sense. We will likely move the pointer to the db itself so it can't get out of sync.

To fix you could go to the database view, and tap "zero db marker". The next upload will push the entire db currently being used up to the website, and the pointer will then be married to the current db.

**Comment by bobzilladev** [comment]
Once you upload the whole new db, you could switch to the other db by toggling that permission for the app, which is possible deep in android settings under the apps section.

**Comment by bobzilladev** [comment]
The runtime permissions model android moved to causes all kinds of havoc like this, very hard to work with.

**Comment by kill0rz** [comment]
> To fix you could go to the database view, and tap "zero db marker". The next upload will push the entire db currently being used up to the website, and the pointer will then be married to the current db.
Unfortunately this did not fix the problem.
I zipped and uploaded everything via website and the networks were parsed correctly, so data isn't lost at all.

Furthermore I moved the app to the sd card and now upload does work again. Thank you for solution :)

**Comment by kill0rz** [comment]
I have to correct myself - upload does not work :(

![hc_001](https://cloud.githubusercontent.com/assets/14353631/25554671/3d3936ba-2cd3-11e7-8cce-f10e095b69f2.jpg)

**Comment by kill0rz** [comment]
But this seems like an error caused by wigle API - upload via website isn't possible as well: Unable to send file: error

**Comment by kill0rz** [comment]
I have to correct my post above: Same error as in first post appeared again, even after resetting the database marker :(

**Comment by bobzilladev** [comment]
What does the app say is the highest marker when app was loaded? If the db is empty, then an upload won't be possible. If it is non-empty then you can reset the marker to zero and upload the entire db.

**Comment by bobzilladev** [comment]
Nevermind, we've found the issue. Version 2.19 should fix. You can side-load it from here if it takes a while to show up in your view of the Play Store.
https://github.com/wiglenet/wigle-wifi-wardriving/blob/master/dist/wiglewifiwardriving-release.apk

**Comment by kill0rz** [comment]
Confirming that this fixed the issue. Thanks :)

**Comment by bobzilladev** [comment]
That's super news! When fixing the case we thought this was, we found this regression that happened in a refactor of the networking code to move to the new api. Thanks for all the bug reports.
