### ISSUE TITLE
On Hamburgher menu filter doesn't work well in Italian version

### ISSUE THREAD

**Issue by Raffaele74** [wiglenet/wigle-wifi-wardriving#128]
**It doesn't work or it is not clear.**
1. Filter ON must be up. It seems to me it doesn't include SSID.
2. Open - Wep -Wpa - Towers are "OR"; but SSID in "AND".
3. If I'm looking for a SSID, it's not enough to write it in the field, but I have to do double-click on Filter ON to get it.
4. App shows me little cluster (eg 3 wifi) with one wifi symbol.
5. If I search "Telecom-4" it shows "Telecom-*".
6. In my mind it is clearer if you don't repeat "show" every time.

I'd like this function working on Global WiGLE (not only my, because it seems to me I cannot view some important wifi). And I need to know where It is important I do wardriving.

I named SPAM WiFi WiFi without pwd and without www. Perhaps you call it "commercial".

![filters](https://cloud.githubusercontent.com/assets/24221053/25701259/e91b4d64-30cb-11e7-9588-5551ba375f98.png)

**Comment by Raffaele74** [comment]
I noticed that app has two filters. One in list and one in map. They are different. Filters on list seems to me doing nothing.

**Comment by Raffaele74** [comment]
It seems to me that app read filter when I get into the function and ca not change it while remaining inside. So filter on / off work, but does not change the criterion (I change, but app ignored; also "nul").

**Comment by Raffaele74** [comment]
I think there is need for something that makes it clear whether the visualized on the page is filtered or not.

**Comment by rksh** [comment]
This issue should be (at least partially) addressed by filter changes in the most recent releases. Please feel free to post feedback here!

**Comment by Raffaele74** [comment]
Hi Handy.
Better but I cannot understand "Mostra SSID ... regolare". Probably it is condition "Not open and not wep and not wpa and not cell". In this case it is "Mostra SSID che NON soddisfano le regole indicate sotto" (in English "Show ssid not satisfying rules expressed below".

**Comment by rksh** [comment]
"Regular Expression" is a term for a specific syntax for string matching - https://it.wikipedia.org/wiki/Espressione_regolare - in this case, an expression that may match one or more SSIDs that can be used as an exclusive ("show only matching") or exclusive ("show only those that don't match") test on the SSID

**Comment by Raffaele74** [comment]
It's same I say. Thanks.

**Comment by rksh** [comment]
closing - I think we've fixed this (If i'm wrong, please open a new bug with a detailed description!)
