### ISSUE TITLE
Network Location not updating current map position

### ISSUE THREAD

**Issue by Raffaele74** [wiglenet/wigle-wifi-wardriving#130]
Whit bottom setting, commands 182 183 don't work.
182 <string name="menu_turn_off_lockon">Non seguire la posizione corrente</string>
183 <string name="menu_turn_on_lockon">Segui la posizione corrente</string>

![screenshot_2017-05-05-09-44-46](https://cloud.githubusercontent.com/assets/24221053/25737402/ed04be04-3177-11e7-8638-db12e2d6f213.png)

**Comment by bobzilladev** [comment]
If you have network positioning on, but not gps positioning, I could imagine the "follow the current position" not updating on the map. This could be tested, would pry involve more plumbing from the location callback to the map view.

**Comment by rksh** [comment]
tested working - attributing fix to location core retrofit for GNSS
