### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Raffaele74** [wiglenet/wigle-wifi-wardriving#131]
"OK" doesn't work. I must go out and return.

![screenshot_2017-05-05-10-51-38](https://cloud.githubusercontent.com/assets/24221053/25739171/13f289c0-3181-11e7-9748-3e0862d95951.png)

**Comment by marmat8951** [comment]
I tried to reproduce this but I couldn't with the actual version, can you check if it has been fixed since you opened the issue? @Raffaele74

**Comment by Raffaele74** [comment]
:-) Solved!
