### ISSUE TITLE
Development for WiGLE always on.

### ISSUE THREAD

**Issue by Raffaele74** [wiglenet/wigle-wifi-wardriving#132]
Wigle consumes a lot of battery, so I must use it intentionally in detection campaigns.
I'd prefer app turns on byself when you need it.
If I said so, it is impossible; but if I say I want app turns in stand by byself when it doesn't need to work, you can do it.

When does it not need to work?

>App can be know byself:
When I'm stationary or still I move very slowly (modify on setting)
When I'm connected to a wifi (to make the sophistication I can put it first, but it should not serve, to realize that I'm hooked to already done)
At certain hours (night, office, ......)

>App need I set:
In some areas (identifiable as towers-area, but perhaps also with 1° GPS).

We accept other ideas.

Annex screenshhot of warning by Android that invites users don't use WiGLE (It send a notification that open this page)
![screenshot_2017-05-09-00-52-36](https://cloud.githubusercontent.com/assets/24221053/25828911/5435a95c-3453-11e7-89c7-cf68f038dad4.png)

**Comment by rksh** [comment]
Requesting re-test with modern release! Thanks for your feedback!

**Comment by Raffaele74** [comment]
Restested. It seems 10% better.
But I think an important target is zero consumption if I dont't move in a location I visited less then x day ago.
So I can have app always on.
You can add a trigger as "working when wifi not connected" or "working out a cell" or "working when speedy over xx" ....

**Comment by rksh** [comment]
Would an application like Tasker and intents help solve this problem? WiGLE supports termination and upload intents now, and Tasker can launch on events as well. What android system events would you like to use to determine whether to scan or not?

**Comment by Raffaele74** [comment]
Tasker drains battery too! But I can.
Better if app does itself.

I'm not a developer, but I viewed apps that works only when I'm walking, I'm cycle, I'm in a car ....
I think that natural working for Wiggle is in a Car with car-charger.

This last is easy with a tasker.

**Comment by rksh** [comment]
closing issue for now - some battery consumption appears device specific, but i believe we've minimized battery usage to the extent possible, considering our mission!
