### ISSUE TITLE
Stat

### ISSUE THREAD

**Issue by Raffaele74** [wiglenet/wigle-wifi-wardriving#133]
I don't understand for a good translation.
I seems to me: (A or B)
> A. I didn't translate well
> B. "37.045 ___" must be write in global stat page

![screenshot_2017-05-12-15-06-08](https://cloud.githubusercontent.com/assets/24221053/25999517/b9554b56-3725-11e7-8ce1-9fa0cbcb96df.png)

**Comment by rksh** [comment]
the location of each network is based upon the aggregate (via trilateration) of multiple observations - this count is the total number of observations you've contributed over all the networks you've observed.

**Comment by Raffaele74** [comment]
Ok. done a pull request with changes.
