### ISSUE TITLE
I don't know if wigle want to do

### ISSUE THREAD

**Issue by Raffaele74** [wiglenet/wigle-wifi-wardriving#146]
The reason I arrived to wigle is interest for national-network-wifi that are developing in old the world (es. Vodafone Wifi). 
Some operators are opening a wifi network on all their router with the same SSID and sell sims that allow access. 
So, like for mobile, it would be interesting to have distinct coverage maps for performance.
With my experience I saw that it would suffice a simple test on/off on internet connection, because wifi has priority over the 4G and so in some cases (many cases) this wifi completely disconnects devices.
What do you think about insert an optional test and bd of them?

**Comment by bobzilladev** [comment]
There is a button on the network's instance view to connect if you have the owner's permission. We wouldn't add anything further, since it's illegal in most jurisdictions to connect to a network without permission, and the nature of wardriving is passive-survey of radio signals in the air.
