### ISSUE TITLE
GPSListener.java make GPS_TIMEOUT and NET_LOC_TIMEOUT editable in settings menu

### ISSUE THREAD

**Issue by bernardladenthin** [wiglenet/wigle-wifi-wardriving#152]
Hi,
it happens to me that I have no GPS in a bus or in the train in the area of bridges very often. I would like to set the timeout independently (in the settings menu). Can you please make the GPS_TIMEOUT and also NET_LOC_TIMEOUT editable in the settings menu? A field for a custom number would be very nice. Thanks in advance and greetings from Berlin.

**Comment by rksh** [comment]
sounds like a good feature!

**Comment by bernardladenthin** [comment]
Hi, can someone please implement this and do a release? I need this very urgent. I'm also willing to donate on a bountysource or something similar. Thanks in advance, Bernard

**Comment by rksh** [comment]
since an arbitrary number could lead to unexpected/hard-to-debug behavior, can we devise a list of "pre-sets" that would fit most practical purposes and keep people from entering numbers that would result in problematic behavior?

**Comment by bernardladenthin** [comment]
Fine, please add at least 1 hour, then I'll can scan in a shopping center also.
Maybe the current settings (10 seconds?), 1 minute, 5 minutes, 30 minutes and 1 hour would be fine for me. Many thanks in advance. Happy scanning 👯‍♂️

**Comment by rksh** [comment]
addressed in commit https://github.com/rksh/wigle-wifi-wardriving/commit/d0ccfdb410dd7f2b4e78087764cbf110fc2ab0bb . testing and review required.

**Comment by rksh** [comment]
will be in next release!

**Comment by rksh** [comment]
PS> no bounty required, but if you like the app, a good rating in the Play Store would be welcome!

**Comment by bernardladenthin** [comment]
I wouldn't buy a smartphone where wigle isn't running. 👍 Many thanks and greetings from Berlin
