### ISSUE TITLE
Login on Android O (8.0.0) Dev Preview 4 fails

### ISSUE THREAD

**Issue by jrdaughe** [wiglenet/wigle-wifi-wardriving#155]
When logging into wigle app on Android O (8.0.0, build OPP4.170623.014), login fails with bad password.  Password works fine on web page on same phone.  Login session was working prior to Android O upgrade, and continued o work after.  After Deauthing the account in the app, and attempting to login again, login fails.

![unknown](https://user-images.githubusercontent.com/30663365/28882842-0fc6b240-7772-11e7-970a-51f6a9c6aadb.png)

**Comment by bobzilladev** [comment]
We've duplicated it, getting a javax.crypto.IllegalBlockSizeException, thanks for the heads up! We'll get it fixed before they roll that out.
