### ISSUE TITLE
"Cancel" Buttons can't actually interrupt HttpUrlConnection

### ISSUE THREAD

**Issue by rksh** [wiglenet/wigle-wifi-wardriving#196]
Once a request has gone to the network library, it is exceedingly difficult to interrupt. We should either replace this library with one that can be correctly interrupted, or dim/disable any cancel buttons during this state.

**Comment by bobzilladev** [comment]
Happy to disallow during a critical section. Swapping out network lib sounds like a lot of work for little win.

**Comment by rksh** [comment]
OkHttp3 looks like the right library, and would simplify some of our networking goo!

**Comment by rksh** [comment]
should be fixed now, but requires testing.

**Comment by bobzilladev** [comment]
This has been released for a while, closing.
