### ISSUE TITLE
split zh l10n into zh-TW & zh-CN, and probably zh-HK

### ISSUE THREAD

**Issue by Artoria2e5** [wiglenet/wigle-wifi-wardriving#201]
Chinese/Mandarin are written in two different scripts in Taiwan (as `Hant`) and China (as `Hans`). The difference is large enough for most applications to divide the language into two categories. Some applications add a separate category for Hong Kong (also `Hant`), which has a lexicon quite different from that found in Taiwan.

**Comment by rksh** [comment]
good note - we welcome improvements as pull requests to strings.xml .  I'm afraid we don't have anyone who can do the translation on the team, but would be happy to incorporate any help you'd be willing to provide!

**Comment by rksh** [comment]
note: happy to create the files if folks are comfortable editing the files, but not creating them; just let us know!

**Comment by rksh** [comment]
split Taiwan and Hong Kong Traditional directories, but translations are still seeded with the core Chinese translation. PLEASE HELP US TRANSLATE THESE THREE FILES!

https://github.com/rksh/wigle-wifi-wardriving/commit/e51b43ece4dd080ed3c8dc3d97df39ce9318a001

**Comment by rksh** [comment]
https://github.com/wiglenet/wigle-wifi-wardriving/pull/214 - should resolve!
