### ISSUE TITLE
Exclude "Scanning turned off" time from Run duration

### ISSUE THREAD

**Issue by goldfndr** [wiglenet/wigle-wifi-wardriving#227]
I think the Run duration amount would be better implemented as only incrementing when Scanning is turned on. Benefits from this:

* If you scan on the way to work, turn off scanning while at work, then resume scanning after work, it wouldn't look like the device was scanning on its own.
* Additional indication that scanning is turned off.
* Easier to roughly calculate average of how often you're seeing APs.

Perhaps a preference toggle between Run duration and Scan duration?

**Comment by rksh** [comment]
good point

**Comment by rksh** [comment]
in the next release!
