### ISSUE TITLE
Improve Cell Data Logging

### ISSUE THREAD

**Issue by rksh** [wiglenet/wigle-wifi-wardriving#229]
Re-evaluate cell data availability and detail available in new Android API releases, improve data logging in client and submitted to server. SignalCheckPro looks like an example of really great insight into cell net info and quality - let's see how much more we can capture/annotate with local data

**Comment by ngoclong19** [comment]
I have a problem with a dual SIM dual standby phone (Nokia 5 2017 model TA-1053, Android 8.1).
- SIM 1 online, SIM 2 unattached: wigle reports cell network of SIM 1. It is OK.
- SIM 1 online, SIM 2 no service, main data SIM is SIM 1: wigle reports cell network of SIM 1, but the network name is blank.
- SIM 1 online, SIM 2 no service, main data SIM is SIM 2: wigle does not report any cell network.
- SIM 1 and SIM 2 online, main data SIM is SIM 1: wigle reports cell network of SIM 1. It is OK.
- SIM 1 and SIM 2 online, main data SIM is SIM 2: wigle reports cell network of SIM 2, but the network name is SIM 1's.
Expected result: can get information about 2 cell networks simultaneously.

**Comment by rksh** [comment]
PS> if you're interested, we'll certainly push this change to the beta channel in the play store before a full release - feedback *very* welcome.

**Comment by rksh** [comment]
https://github.com/wiglenet/wigle-wifi-wardriving/pull/236 will probably serve as the basis for a new release; thanks for support and advice everyone!

**Comment by ngoclong19** [comment]
I have tried version 2.30. This version looks promising. I can get 3 network names at the same time (GSM-LTE/WCDMA-WCDMA for SIM1, LTE-LTE for SIM2). Thank you for your hard-working guys!

Can I increase the observation number displayed? When I go into a network detail, the observation number seems to be fixed at 512.

**Comment by rksh** [comment]
That's great news. Thanks for the testing and feedback! We'll look into the observation display in a subsequent release.

**Comment by rksh** [comment]
Hi, it looks like the 512 observation limit is actually a safety measure we took because devices were locking up trying to render too many items.  It might be hard to fix this, but we're open to PRs. We can also insure that the points are ordered most-recent-first.

**Comment by rksh** [comment]
ordered results in https://github.com/wiglenet/wigle-wifi-wardriving/pull/240

**Comment by rksh** [comment]
closing for now. I'm sure we can do more, but let's file new tickets on detailed problems!
