### ISSUE TITLE
Split OUI table by length?

### ISSUE THREAD

**Issue by goldfndr** [wiglenet/wigle-wifi-wardriving#241]
Currently, [network.getOUI](https://github.com/wiglenet/wigle-wifi-wardriving/blob/master/wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/model/Network.java#L246) performs three lookup passes over the entire OUI table (worst case, especially if missing) to retrieve a manufacturer.

Would it make more sense to split the table by lengths into three tables? Then, only the 9 character length table would be checked for the 9 character substring, and the 7 for the 7, and the 6 for the 6. It could be further optimized by only checking the 9 character length table if the first six characters matched the magic number; that could also indicate a missing value if the latter three of nine characters didn't match (magic match but value not in table).

**Comment by bobzilladev** [comment]
the long term plan is to ship as an sqlite file like the new mcc/mnc data, then the whole thing doesn't need to be in memory and has an index. just didn't get to it this release.

**Comment by bobzilladev** [comment]
We have had issues with the writing a static table path for mcc/mnc, so won't be converting the oui to that scheme. That said these are up to 3 O(1) hashtable lookups, so it's not a performance worry. Going to close this out.
