### ISSUE TITLE
Please make user data collaboration possible

### ISSUE THREAD

**Issue by untotren** [wiglenet/wigle-wifi-wardriving#244]
I have been using this for a while, uploaded a lot of data. I want to be able to see what my fellow users have uploaded as well. Can you please make this a feature or if not, can any other users point me to an app that allows collaboration? I don't collect this data just for one organization to hoard it, I collect it for it to be used by all, but lately this is feeling like a 1 way relationship.

**Comment by bobzilladev** [comment]
In the app:
Map View -> Magnifying Glass -> Map Overlay Settings -> Show Discovered Networks on Map [none, Mine, Others, All].

On the website:
https://wigle.net/map
https://wigle.net/mapsearch
https://wigle.net/search

From the API:
https://api.wigle.net/
https://api.wigle.net/swagger

Is there a new feature you are requesting?

**Comment by untotren** [comment]
@bobzilladev Thank you honestly, I appreciate that you took the time to list the links and include instructions, sincerely, that is nice of you.  So, this may be easier to say what I wish to achieve. I was hoping to type a city like amsterdam, cause I am travelling, and dl a .csv or something like that so I can load the open networks into a device. Is this possible?

**Comment by bobzilladev** [comment]
You could hit the api to search for networks in a certain area with certain characteristics. We don't know what networks are ok for folks to use, we don't get permission from operators, so just having a list of non-encrypted networks isn't super useful.

**Comment by untotren** [comment]
Permission? Is that the laws in europe? Most wifi in public spaces that is open and doesnt have a captive portal stating terms I usually assume is open for use as long as the use is legal.

**Comment by bobzilladev** [comment]
Laws do vary by locality, and we've heard lawyers argue both sides, so it's up to you to not be in violation.

As a concrete feature request, being able to do api searches via the mobile app would be a nice thing. We currently have a view that does searches in the local database, but not one that hits the server sid.

**Comment by rksh** [comment]
Just in! The WiGLE Magic (8) Ball project - https://github.com/wiglenet/m8b - allows users to share and combine location data. The beta branch of this project now allows zero-keyed export of your local observation database as an m8b file suitable for integration with other users exported m8b. .m8b files are a non-reverseable artifact that lets your query a list of BSSIDs to attempt to estimate location.

**Comment by rksh** [comment]
This feature will be available in the next beta release of the app - heads up!

**Comment by rksh** [comment]
api searches full integrated in new release!
