### ISSUE TITLE
Notification hard to read (white text on grey background)

### ISSUE THREAD

**Issue by designer2k2** [wiglenet/wigle-wifi-wardriving#281]
Hello,
![grafik](https://user-images.githubusercontent.com/1591573/47962402-9b0fa500-e01c-11e8-838e-2a02c38e6a3f.png)
this is how the notification from release 2.38 looks on a Android 8  Huawei P10.
(below is another app, to show the difference)

Its nearly not possible to read the PAUSE and UPLOAD buttons, as they are white text on grey background

**Comment by bobzilladev** [comment]
Odd that they don't respect the pallet for the notification there. We'll see if we can fix it.

**Comment by rksh** [comment]
could you tell us on what android version you're seeing this issue ?
Cheers!

**Comment by designer2k2** [comment]
hello, as stated above, Android 8.0, on a Huawei P10 running EMUI 8.0

**Comment by designer2k2** [comment]
i guess its the use of Android Ressources:  android.R.drawable.ic_media_pause  
But i cant find a example on how they look in EMUI vs stock Android

**Comment by rksh** [comment]
from Essential PH-1 Oreo:
![screenshot_20190102-121816](https://user-images.githubusercontent.com/880022/50610886-4e641100-0e89-11e9-95c0-f6e24c7c815f.png)

**Comment by rivermont** [comment]
Huawei Honor 6x running Nova.

![image](https://i.imgur.com/Z82GsiJ.png)

**Comment by bobzilladev** [comment]
Hopefully happy at this point, closing.
