### ISSUE TITLE
Consider using OSM as basemap

### ISSUE THREAD

**Issue by rivermont** [wiglenet/wigle-wifi-wardriving#298]
As of [July last year](https://developers.google.com/maps/billing/understanding-cost-of-use) (2018), Google Maps API is now pay-as-you go for large scale usage. WiGLE uses Google Maps tiles as a basemap for the main site and in-app displays. As far as I can tell Google does not sponsor WiGLE and thus the requests are being paid for somehow.  
It seems that WiGLE *used* to use OSM tiles per #56 and #61 but switched to Google at some point (likely due to server reliability and data consistency which is understandable). However unless there are other reasons (which is probable), would it not be viable to switch to OSM tiles, either fully or as an option?

**Comment by bobzilladev** [comment]
As you say, we are large scale, so we can't use OSM's servers, so we have to run our own, which is a royal pain to setup and keep running. That said, as goog is now punching us in the wallet we may be forced to spin one up again.

**Comment by goldfndr** [comment]
There is another alternative: you could use [a commercial OSM* tile provider](https://switch2osm.org/providers/).

*Some providers, such as Mapbox, might use other sources in addition to OSM; a good example is digital elevation models for contours and/or hillshading.

(As an aside, I'm still wondering when [Esri's vector tiles](http://www.arcgis.com/home/item.html?id=3e1a00aeae81496587988075fe529f71) are going to come out of beta; they're supposed to be "freely available" when that happens, but they don't disambiguate "freely" to gratis vs libris.)

**Comment by rivermont** [comment]
Mapbox has made some amazing things and they are very good at consolidating data sources. I hadn't thought of them at first but they would actually be a really good solution. I can't say how their commercial pricing compares to Google's.

**Comment by rksh** [comment]
we continue to have difficulties keeping OSM updated and running. considering recent google pricing changes, we'll have to re-evaluate.

**Comment by goldfndr** [comment]
Esri's OpenStreetMap vector basemap [is now in general release](https://www.esri.com/arcgis-blog/products/arcgis-online/mapping/whats-new-with-openstreetmap-basemap-march-2019/) (although [each item in the group](https://www.arcgis.com/home/group.html?id=5e0d56e27d7e4a68955d399ca96c41cb#overview) still uses the phrasing "When fully released", so I hadn't noticed).

There are sample web deployments [via Tangram](https://www.jonahadkins.com/esri/cartography/openstreetmap/2019/03/28/esri-tangrams.html) or [Esri Leaflet](https://esri.github.io/esri-leaflet/examples/vector-basemap.html). Android deployment *might* require [the ArcGIS Runtime SDK](https://developers.arcgis.com/android/10-2/guide/use-arcgis-basemaps.htm) which presumably involves [specific licensing](https://developers.arcgis.com/android/10-2/guide/license-your-app.htm) (not that the web deployment wouldn't, of course).

**Comment by bobzilladev** [comment]
We did end up switching the website off of google maps. The android app still uses google maps, and likely will continue to, unless they start punching our wallet with that too.
