### ISSUE TITLE
Show satellites used/seen in dashboard view

### ISSUE THREAD

**Issue by goldfndr** [wiglenet/wigle-wifi-wardriving#322]
There's plenty of room to show a count of satellites used and seen in the dashboard view near the satellite icon. It would assist in showing how good the position fix is.

**Comment by rksh** [comment]
adding satellite count added in https://github.com/wiglenet/wigle-wifi-wardriving/pull/323

**Comment by goldfndr** [comment]
Thanks for the number of seen. Looks like the number of used isn't straightforward; [usedInFix(\)](https://developer.android.com/reference/android/location/GpsSatellite.html#usedInFix()) [(newer API)](https://developer.android.com/reference/android/location/GnssStatus.html#usedInFix(int)) would need to be checked for each satellite to create a sum.

**Comment by rksh** [comment]
#339 - you're getting your wish!

**Comment by goldfndr** [comment]
I've been meaning to respond to this. The current output just has *used* rather than *used* and *seen*. Could you [include both](https://github.com/wiglenet/wigle-wifi-wardriving/issues/322#issue-423537903), with a slash between? (In other words, could getSatCount() return a string rather than an int, perhaps renamed to getSatCounts() or similar?) This would probably require the Network List view to have the "Sats:" label on a separate line.
