### ISSUE TITLE
[BUG] Bluetooth GPS locations are unreliable

### ISSUE THREAD

**Issue by rksh** [wiglenet/wigle-wifi-wardriving#329]
This requires further exploration - the transient nature of Bluetooth networks may mean that a reliable GPS fix isn't present at the time of discovery, or there may be a timing condition from driving GPS fixes (and observation LERPing) from the WiFi thread.

**Comment by bobzilladev** [comment]
@rksh Has this been taken care of by the various fixes over the past 7 months?

**Comment by rksh** [comment]
not convinced - hard to tell.

**Comment by rksh** [comment]
server-side fixes with clustering should improve this. closing for now, will investigate specific cases.
