### ISSUE TITLE
Inspect network/device objects

### ISSUE THREAD

**Issue by Lambo212** [wiglenet/wigle-wifi-wardriving#337]
Where exactly in the code are the networks/devices being added to a collection to be uploaded to the Db? 

I would like to inspect each network/device before it gets uploaded however cannot figure out where in the code this is happening please point me in the right direction!

Thanks :)

**Comment by rksh** [comment]
check out [ObservationUploader](https://github.com/wiglenet/wigle-wifi-wardriving/blob/master/wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java) - particularly [writeFileWithCursor](https://github.com/wiglenet/wigle-wifi-wardriving/blob/master/wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/background/ObservationUploader.java#L441)

**Comment by rksh** [comment]
Hopefully this addresses the issue - closing for now, feel free to open a new ticket with the next question if needed!
