### ISSUE TITLE
Line 362 typo

### ISSUE THREAD

**Issue by Mpegforever** [wiglenet/wigle-wifi-wardriving#347]
Hello.
Line 362 now says "scludi i MAC". The letter E is missing. It should be "Escludi i MAC"
Regards,
          Alex

**Comment by bobzilladev** [comment]
Will be fixed in next version, thanks!
https://github.com/wiglenet/wigle-wifi-wardriving/commit/a0f9b98d7b8759b47a22b7145aa41506708d9a56
