### ISSUE TITLE
Entries with bssid of 00:00:00:00:00:00

### ISSUE THREAD

**Issue by xenoxaos** [wiglenet/wigle-wifi-wardriving#37]
Occassionally, I will get a SSID found with sometimes different SSIDs but with the bssid of 00:00:00:00:00:00. This will stay in the currently found SSIDs even after the AP is no longer near. If I open the AP to show the known locations of the AP, it looks like a track of where I've been (since it records the AP of being at every location I've been at). If you would like, I can provide multiple screen shots of this for you.

**Comment by bobzilladev** [comment]
There's no harm in collecting this data, it may prove to be interesting. Closing this issue.
