### ISSUE TITLE
post-Android-10 WiFi activation on startup makes application un-exitable

### ISSUE THREAD

**Issue by rksh** [wiglenet/wigle-wifi-wardriving#377]
Android 10 removed the ability to simply activate WiFi on launch (and deactivate on exit). WiGLE worked around this by adding a call to access preferences automatically when the app was launched with WiFi inactive, but this results in weird edge cases. Note, these cases do not appear soluble short of reboot (returning to/relaunching app, selecting "done" does not remedy the issue, nor does terminating the application via the launcher).

1. (precondition: deactivate WiFi)
   a. launch application
   b. hit home button while pseudo splitscreen present
   <application icon/notification now permanently resident, in spite of exit command>

2. (precondition: deactivate WiFi)
   a. launch application
   b. hit home button
   c. attempt to re-enter the application via icon or notification
   d. toggle wifi, select "done"/"save"
   e. select "exit" from menu.
   <application icon/notification now permanently resident, in spite of exit command>

3. (precondition: deactivate WiFi)
   a. launch application
   b. toggle wifi when presented in pseudo splitscreen but *do not* select "done"/"save"
   c. hit home button
   <application icon/notification now permanently resident, in spite of exit command>

**Comment by bobzilladev** [comment]
Guessing the settings is a sub-view of the wigle process, don't know if we can find and stop that from running, since it's a new hack in android 10 to pop that up.

**Comment by bobzilladev** [comment]
Soon we'll be able to just flip on wifi again, goog is going to fix it in the next android 10 patch:

"Hello. This issue has been fixed and will be available in a future android release.
It was reverted previous behavior (pre Android 10), i.e no new permission needed for DO apps to turn on/off wifi.
It will be available in Dec QPR patch for Android 10 on Pixel devices."

https://issuetracker.google.com/issues/141011684

**Comment by rksh** [comment]
thought https://github.com/wiglenet/wigle-wifi-wardriving/pull/384 might fix the current behavior -looking forward to making this a corner case.

**Comment by rksh** [comment]
looks like this is going to remain an issue with the .0 release of Android 10, fixed in 10.1
