### ISSUE TITLE
Exports can't be found in file explorer

### ISSUE THREAD

**Issue by wvanderp** [wiglenet/wigle-wifi-wardriving#378]
I want to export my database to csv. While it succeeded, I couldn't find it in the file explorer.

So, to understand why I couldn't find the file is started reading the source code. This led me to ObservationUploader.java line 660 where the file output is set to private. 

I understand this choice because the same function is used to write the files before upload and that would just clutter file system but with an export being able to find the file is kind of important.

So maybe we can pass a parameter to the function that informs it when it needs to be private and when not

**Comment by bobzilladev** [comment]
There is a hasSD check first, so if the app was authorized to use SD storage it will write exports to the logical SD area which would be readable by other apps.
In Android 11 they are planning on removing the SD concept entirely, making a new, complicated, and so far clunky interface/UI to deal with application files, so we all have that to look forward to.

**Comment by DaniloNC** [comment]
I am also having the same problem after a factory reset, before I was running Android 10 without any problems (upgraded from pie)


Pixel 2
Android 10 QP1A.191105.004
Wigle 2.48
Permissions fully granted before the first usage.

![Screenshot_20191111-233307](https://user-images.githubusercontent.com/405967/68645116-9eb1f380-04dc-11ea-8b4c-d488ad0f13be.png)
![Screenshot_20191111-233340](https://user-images.githubusercontent.com/405967/68645117-9eb1f380-04dc-11ea-91d0-43e32f388a46.png)

**Comment by bobzilladev** [comment]
They went earlier than expected and locked down the pixel phones already to only be able to access internal storage. There's a new scheme for sharing files that we're going to have to adopt, but it's non-trivial, so hasn't been done yet.

**Comment by inthenoise** [comment]
Do you know of any hacks around this that I could patch into my local build?

**Comment by DaniloNC** [comment]
Is the backup option disabled related to this issue?
![Screenshot_20191216-222227](https://user-images.githubusercontent.com/405967/70964768-b5ef7e00-2052-11ea-802d-8c4d688039e6.png)

**Comment by rksh** [comment]
the backup button is related to the fact that without external storage, it's unclear what a "useful" location for a backup would be. Release 2.50 now has features to offer file sharing for CSV, KML, GPX, M8B and external storage for SQLITE databases. Because the database can be quite large, and because direct sharing from database directories is surprisingly difficult, backup options for local-storage databases, but we're looking into options!
