### ISSUE TITLE
Client does not store most accurate data

### ISSUE THREAD

**Issue by LukeOwncloud** [wiglenet/wigle-wifi-wardriving#39]
When starting WiGLE Wifi and a GPS position is available, it immediately starts scanning.
However, when later (maybe a few seconds) the same APs a found but with a more precise GPS position, I noticed that this new scan is ignored. 

I would expect my local DB to be updated whenever I find an existing AP with a less accurate position (or a weaker signal). This would be especially helpful when "war-walking".

**Comment by bobzilladev** [comment]
We added this at some point, closing out.
