### ISSUE TITLE
How to calculate the location of the Ap? In what class do you calculate?

### ISSUE THREAD

**Issue by darkalexpp** [wiglenet/wigle-wifi-wardriving#394]
I want to know how and where it calculates the position of the AP based on RSSI data

**Comment by bobzilladev** [comment]
For this app the calc is simple:
https://github.com/wiglenet/wigle-wifi-wardriving/blob/master/wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/db/DatabaseHelper.java#L895

Server side the calculation is more complicated, talked about in the FAQ:
https://wigle.net/faq/#how-triangle
