### ISSUE TITLE
No wiglewifi directory for current sqlite db since Android 10

### ISSUE THREAD

**Issue by igordcard** [wiglenet/wigle-wifi-wardriving#395]
My primary way of backing up the database is through a tool that backs up whichever directories I add to it. Since the "wiglewifi" directory is no longer being updated after Android 10, I can't backup the database anymore. Furthermore, it's apparently not possible to it in any other way (as in, the actual sqlite database).

This issue also seems to have been mentioned in: https://wigle.net/phpbb/viewtopic.php?f=13&t=2727

Will there be some workaround to get the db outside of Android's protected internal data or what's the plan?

**Comment by rksh** [comment]
Google's new filesystem permission model prevents us from continuing to write to external storage or even to access it. Unfortunately, our options for work-around are somewhat limited, but we've already incorporated and tested a patch https://github.com/wiglenet/wigle-wifi-wardriving/pull/391 to be included in the next release. This will allow us to backup databases to any preferred third party - including Google Drive, Box, DropBox, OneDrive, and Spider Oak (all names trademark their respective owners).  If you have additional concerns, don't hesitate to clarify in a new ticket!
