### ISSUE TITLE
Google's new filesystem permission model prevents us from (...)

### ISSUE THREAD

**Issue by igordcard** [wiglenet/wigle-wifi-wardriving#397]
Google's new filesystem permission model prevents us from continuing to write to external storage or even to access it. Unfortunately, our options for work-around are somewhat limited, but we've already incorporated and tested a patch https://github.com/wiglenet/wigle-wifi-wardriving/pull/391 to be included in the next release. This will allow us to backup databases to any preferred third party - including Google Drive, Box, DropBox, OneDrive, and Spider Oak (all names trademark their respective owners).  If you have additional concerns, don't hesitate to clarify in a new ticket!

_Originally posted by @rksh in https://github.com/wiglenet/wigle-wifi-wardriving/issues/395#issuecomment-573485406_

Will that patch be enough to backup the database in its original sqlite format?
And how is the import going to work (apart from downloading from wigle.net)?

**Comment by rksh** [comment]
yes,sqlite backup works in development, will be in the next release.
we don't have a non-WiGLE import option in the current codeline (although I suppose nothing stops you from loading data into your database manually) - what use case(s) did you have in mind?

**Comment by igordcard** [comment]
Thanks. Just want to make sure it will continue to be possible to scan, backup and reimport to new devices, with unaltered original data, even if something was to happen to wigle.net itself.

**Comment by igordcard** [comment]
I've successfully exported the db to gdrive today thanks to, I assume, the fix from patch #391. Thanks, I'm closing this.

**Comment by rksh** [comment]
cool - more user-facing stuff scheduled for the next release to try and mitigate all this - see https://twitter.com/wiglenet/status/1224407782062837762 for details.
