### ISSUE TITLE
Wigle 2.50 beta without Google maps

### ISSUE THREAD

**Issue by DaniloNC** [wiglenet/wigle-wifi-wardriving#402]
Hi,

I don't know if this was intended but the version 2.50-beta does not have Google maps as the image below:

![Screenshot_20200131-194145](https://user-images.githubusercontent.com/405967/73584938-ce302680-4461-11ea-8c91-1b49c4519882.png)

This happened to the version uploaded to the Google play store

**Comment by bobzilladev** [comment]
Gah, wrong binary. 2.51 rolled out now, thanks for report.
