### ISSUE TITLE
Broken in Android 11 Developer Preview 2

### ISSUE THREAD

**Issue by NatoBoram** [wiglenet/wigle-wifi-wardriving#412]

**Comment by bobzilladev** [comment]
Haven't spun that up yet, could you be specific in what things are broken?

**Comment by NatoBoram** [comment]
Yeah, sure, here's a [quick video](https://bafybeihhq4rgjlxxnjmm7jub6h343dflrevtcnqcxuk3guxxcwnd4glsly.ipfs.dweb.link/wigle_crash.mp4) of the crash happening.

**Comment by bobzilladev** [comment]
after a crash it should bring up an upload activity with recent logs and detailing the crash, which you could send to us (wigle-admin).

**Comment by rksh** [comment]
should be fixed in current releases, although some outstanding issues with scan delay and autostart have been listed in their own ticket (https://github.com/wiglenet/wigle-wifi-wardriving/issues/435)
