### ISSUE TITLE
The labels of some menu tabs are not displayed

### ISSUE THREAD

**Issue by drygdryg** [wiglenet/wigle-wifi-wardriving#414]
I recently [pull requested](https://github.com/wiglenet/wigle-wifi-wardriving/pull/413) improvements for Russian translation, but it seems to causing an error displaying some menu tabs. I could not find out the reason for this behavior. I was running the app on my Redmi 5A with a 5 inch screen 
![Screenshot_20200323-233119_Trebuchet](https://user-images.githubusercontent.com/43933400/77360702-e421df80-6d5e-11ea-8cb3-9672947f0113.png)

**Comment by bobzilladev** [comment]
Fixed up, the menu needs shorter words to start with.
https://github.com/wiglenet/wigle-wifi-wardriving/commit/764e5afc0f799aa39dc7f3c040512d79cee2d9e6
