### ISSUE TITLE
Fix request for Google maps api sdk crash

### ISSUE THREAD

**Issue by clientenq** [wiglenet/wigle-wifi-wardriving#416]
Due to the following issue (Google Maps SDK is crashing) wigle wifi wardriving is crashing when selecting the google map. This issue started this week via Google, affecting multiple apps including wigle wifi wardriving. The issue is partially resolved. The remaining crashes are due to client-side caching, which is why Google recommends the workarounds mentioned in the issue. Without the workaround it seems all clients have to clear all application data. This is not a convenient issues since this would mean any client without a wigle account will not be able to restore the database via the app.

Proposed solution:
Create background clearing of affected google maps data. Not affecting user data such as database storage, setting, etc.

Google issue tracker:
https://issuetracker.google.com/issues/154855417
https://issuetracker.google.com/issues/154855417#comment388

**Comment by bobzilladev** [comment]
aye, we're trying to get the workaround out. sounds like goog will add a fix into google play services to fix it, but we might as well push as well. version 2.53 will have the workaround.
https://github.com/wiglenet/wigle-wifi-wardriving/commit/340a2cf8efa7f95a3a0c7f6dffd7ea91f07177e4

**Comment by bobzilladev** [comment]
2.53 is in the beta channel now, if you're subscribed to that.

**Comment by bobzilladev** [comment]
2.53 in prod now.
