### ISSUE TITLE
nothing works without gps, even exporting other data

### ISSUE THREAD

**Issue by ilyapashuk** [wiglenet/wigle-wifi-wardriving#421]
if app can't get gps lock, i can't export any other data.
please add option to fully ignore gps and continue work with other data.

**Comment by rksh** [comment]
band-aid: you can still export your SQLite database for access and query, although that's non-trivial to use. Tell us a little more about the use-case(s) you'd like to support? Specifically, all of our current export formats are geared toward geolocated data (KML and CSVs are lat/lon based). What would a useful non-located export format for your purposes look like for your purposes?

**Comment by rksh** [comment]
absent details of what non-GPS-oriented export options (apart from SQLite database export), slating this ticket for closure.

**Comment by rksh** [comment]
closing due to lack of feedback.
