### ISSUE TITLE
'Delayed' scanning on Android 10

### ISSUE THREAD

**Issue by melbournefan** [wiglenet/wigle-wifi-wardriving#430]
I'm running Android 10 with ColorOS 7.1 and WIFI throttling switched off but scans still seem to be delayed by around 2-6 seconds, sometimes with a 'DB Queue' count above 0. GPS and 'WiFi Scanning' are switched on but it still seems to be 'delayed'.

I've attached some of the log, tho I can't find much online

Thanks

```

16:56:18.979 main] Location provider change, scheduling scan
16:56:19.008 main] startScan returned false. last response seconds ago: 3.471
16:56:19.047 main] startScan returned false. last response seconds ago: 3.511
16:56:19.851 main] Tried to update BTLE batch in improbably short time: 27
16:56:20.055 main] startScan returned false. last response seconds ago: 4.518
16:56:20.505 main] wifi receive, results: 13
16:56:21.063 main] startScan returned true. last response seconds ago: 0.573
```

**Comment by melbournefan** [comment]
And an update.. It seems that if I switch WiFi off in the settings and switch off WiFi searching in ColorOS that it fixes the issue completely.. Though then the phone will only be scanning Bluetooth..

**Comment by rksh** [comment]
This seems to behave somewhat like the scan throttling in core android - is there an equivalent setting in color OS? https://www.netspotapp.com/help/how-to-disable-wi-fi-throttling-on-android-10/

**Comment by rksh** [comment]
Flagging this for further input - appears well beyond our control. Do WiFi networks appear in the list interface with those settings disabled?

**Comment by rksh** [comment]
closing as outside the scope of our software.
