### ISSUE TITLE
Bug: tts speaks in english instead of german

### ISSUE THREAD

**Issue by Dtrieb** [wiglenet/wigle-wifi-wardriving#438]
My Device and tts language is german, but wigle speaks English, tts is english.

I want to set it p.e. to german.

**Comment by rksh** [comment]
interesting - this should work. can you share device, OS version with us? Specifically, some FOSS, 3rd party Android versions probably won't have the support we need.

**Comment by Dtrieb** [comment]
Phone: Google Pixel 4 XL
OS: Stock Android 11
Nothing else special ...

The language in the Wigle is set to german.

**Comment by rksh** [comment]
working on a solution in https://github.com/wiglenet/wigle-wifi-wardriving/pull/440 - watch this space.

**Comment by rksh** [comment]
tested - resolved in https://github.com/wiglenet/wigle-wifi-wardriving/pull/440 - marked for release 2.56

**Comment by rksh** [comment]
released in new betas! closing.
