### ISSUE TITLE
[Feature Request] Import sqlite on Android 10

### ISSUE THREAD

**Issue by jloehel** [wiglenet/wigle-wifi-wardriving#450]
I bought a new phone. I am trying to import an old database but I can't find the sqlite file. What is the current status? How can I migrate?

**Comment by bobzilladev** [comment]
Yeah, google now forces the data to be in the app's internal storage and not the virtual sdcard. We added a full export: 
3-horizontal-line menu -> Database -> Backup Database. After that completes it will pop up a share dialog to allow the file to be emailed or other ways to transmit off the device.

We don't have a way to import that data back in to a new device at this time, unfortunately. On that same Database panel there is an "import observed" though, which will pull in data from the wigle servers. That doesn't grab every field, but would let the device know what networks are new to you or not.

**Comment by jloehel** [comment]
> We don't have a way to import that data back in to a new device at this time, unfortunately.

Any ideas or plans? How can I help?

**Comment by bobzilladev** [comment]
Don't think there's a way to write the to internal app storage without rooting the device. So the "import observed" button is currently the only way forward. Otherwise would need an import mechanism coded into the app which I'm not sure when we would be able to get to doing.

**Comment by jloehel** [comment]
> Don't think there's a way to write the to internal app storage without rooting the device. So the "import observed" button is currently the only way forward. Otherwise would need an import mechanism coded into the app which I'm not sure when we would be able to get to doing.

Okay, thanks for the feedback. It would be really awesome if you (we) could add such a functionality.

**Comment by rksh** [comment]
all contributions are welcome! We have no distinct guidelines, but we use rely on fork-and-PR - gives us a chance to review, suggest any changes, and merge in a way that kinda-lines up with our release cadence. Bobzilla and I are probably right reviewers to add.

**Comment by rksh** [comment]
probably cold comfort, but you can also import individual uploads from your uploads screen as well - click and indicator with a grey left-side indicator and a green right-side indicator (successfully uploaded to the server, not from this device) to download the upload data in question to the new device. If someone wanted to implement a restore-all-networks-observed-to-this-device, this could work, although it's worth noting that beyond a certain point, shoving everything into your local database is not advisable - it'll slow down scanning performance, risk maxing device storage quotas under the new storage rules @bobzilladev mentions above.

**Comment by bobzilladev** [comment]
Going to close this as it's basically asking for full server import, which is in this issue: https://github.com/wiglenet/wigle-wifi-wardriving/issues/10
