### ISSUE TITLE
Application shuts off bluetooth on exit even when bluetooth was enabled at launch

### ISSUE THREAD

**Issue by rksh** [wiglenet/wigle-wifi-wardriving#452]
forum post on WiGLE.net:
https://wigle.net/phpbb/viewtopic.php?f=13&t=2808

**Comment by barry99705** [comment]
Phone updated to android 11 yesterday, still turns off bluetooth when exiting.  This is a Note 20 Ultra on At&t if that matters.

**Comment by rksh** [comment]
requesting a retest of this issue with v2.60 - some fixes included there should address this!

**Comment by barry99705** [comment]
Yes it did!  Just noticed yesterday that it didn't kill bluetooth when
shutting wigle down.  Thanks!!!

**Comment by rksh** [comment]
GREAT! As we were unable to reproduce this one on test devices, we were pretty stumped. The short version is that there are states other than "on" and "off" for bluetooth. The original test was just "if bluetooth isn't on at startup, shut it down on exit" - it appears that some Android devices don't quickly or cleanly transition, and may even remain in "starting up" or "shutting down" while running - probably works fine, but it confused our test. Should you find more corner cases, please let us know, including as much detail around that corner case as possible. Closing this ticket as fixed!

**Comment by barry99705** [comment]
Thanks!
