### ISSUE TITLE
A display bug

### ISSUE THREAD

**Issue by franklinbill** [wiglenet/wigle-wifi-wardriving#459]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the lower part of the text overlaps with each other, which may be an adaptation error. It is possible that the text and display are too large.
App version is 2.51, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, _**font size and display size**_ are the **_largest_** ! ! !, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![wigleandroid](https://user-images.githubusercontent.com/18572115/103098452-c2cf8600-4645-11eb-8c3d-1da6a3e368b9.png)

**Comment by rksh** [comment]
fix now released - thanks for the report!
