### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [wiglenet/wigle-wifi-wardriving#460]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text of is blocked, which may be an adaptation problem. It is estimated that the height of the text component needs to be set to be adaptive to the text size.
App version is 2.51, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, _**font size and display size**_ are the **_largest_** ! ! !, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![bug-wigleandroid-2](https://user-images.githubusercontent.com/18572115/103098572-31acdf00-4646-11eb-8950-b2eeb4de4da3.png)

**Comment by rksh** [comment]
weird; we're not even doing android responsive layout wrong in that view. ;) Will test and see what's up.

**Comment by rksh** [comment]
oh, here we are. https://stackoverflow.com/questions/11243867/android-last-line-of-textview-cut-off - don't have a Nexus 6 with which to test, but the behavior seems ok on other test devices with this fix applied.

**Comment by rksh** [comment]
fix now released! thanks for the report!
