### ISSUE TITLE
All SSID, GPS, RSSI and measurement times?

### ISSUE THREAD

**Issue by crroush** [wiglenet/wigle-wifi-wardriving#461]
I can only seem to get some sort of "average" gps location of AP when I export to the csv file.  I am really interested in having an output that provides SSID, GPS, RSSI and Time.  So if a measurement comes in say every second I would have an output for each SSID that is detected. 
Is that data stored somewhere that I can get access to?

**Comment by bobzilladev** [comment]
Sure! Data on individual observations is kept in the 'locations' table within the sqlite db the app keeps. You can export the whole db file with "Backup Database" then use any of many sqlite tools to explore the data from there.

**Comment by crroush** [comment]
@bobzilladev I have been looking at that table, it seems to update the position it receives for each network, maybe my sqlite kung-fu is lacking, but I am not seeing in the table where you store every time instance / power level for a given SSID.  It appears in the DatabaseHelper.java to update with the "last location, last time, last level".  
I am just doing `select * from location;`, all of the mac addresses are unique.

**Comment by bobzilladev** [comment]
The `network` table has the latest observed data per-network. The `location` table records multiple observations for given networks. Hopefully you were able to get the data out you needed.
