### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [wiglenet/wigle-wifi-wardriving#462]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Korb** [comment]
There are currently no screenshots on the app's F-Droid page:

![Image](https://github.com/user-attachments/assets/f597d0ff-61bb-4a68-923b-7491f5668db3)

**Comment by rksh** [comment]
why are you tagging me in a 5 year old closed issue? We are not the maintainers of the F-Droid listing.
