### ISSUE TITLE
Upload to Wigle.net is not working

### ISSUE THREAD

**Issue by Omcsesz** [wiglenet/wigle-wifi-wardriving#463]
Hello, team!

When I try to upload my scan results to wigle.net, I get the following error message (see attachment).
![Screenshot_20210105-130531](https://user-images.githubusercontent.com/1839739/103644502-c5d84980-4f56-11eb-9daa-c61ce221be62.jpg)

Am I missing something?

**Comment by bobzilladev** [comment]
There needs to be new observations with gps coordinates since the previous upload in order to upload again. No reason to upload an empty file.

**Comment by Omcsesz** [comment]
Thank you!
