### ISSUE TITLE
Export problems

### ISSUE THREAD

**Issue by skr-amp** [wiglenet/wigle-wifi-wardriving#473]
When exporting to CSV, if the ssid field contains non-Latin characters, they are replaced with the"? " character. Although they are stored correctly in the sqlite database.

**Comment by rksh** [comment]
We'll look into correct UTF-8 CSV support; good catch!

**Comment by rksh** [comment]
server-side UTF-8 support pending review.

**Comment by bobzilladev** [comment]
Server side is updated, client side is updated in #642, will be in next release.
