### ISSUE TITLE
App doesn't save gzipped csv files in accessible location on Android 10

### ISSUE THREAD

**Issue by dziban303** [wiglenet/wigle-wifi-wardriving#478]
Upon uploading a run, the app exports the run as a gzipped csv file. In the past—on Android 9—a popup appears showing the filename and directory, which turns out to be the /wiglewifi directory; it can then be accessed through other means. 

However, on Android 10, upon uploading the run, a popup appears saying the file has been saved but does not show a location, and it is not in the wiglewifi directory or any other directory accessible without root. I can't find a setting anywhere in the app to control this. The app has all permissions requested, including storage access.The sql database seems to be kept in the /wiglewifi directory so it's presumably not a permissions issue. 

So how can I get it to output individual runs to that (or another accessible) directory?

**Comment by bobzilladev** [comment]
A10 changed how file storage is done, the app can't save to the psuedo sdcard anymore. We've added export functions from the database panel so you can get a copy of the database as kml/csv, or use "backup database" to copy the whole sqlite file and share it to yourself via whatever communications apps are on the device. Also on the uploads panel you can press the 3-dots share button to get a copy of the upload data as kml shared.

You can also get at the app-storage area through developer tools, to get at the upload files directly.

**Comment by bobzilladev** [comment]
Hrm, that may have been bad advice, likely only works while in debug mode while developing.
https://stackoverflow.com/a/16461386

**Comment by dziban303** [comment]
Ah well. Thanks for the help, I'll just export the runs manually for the ones im interested in. Thanks again!
