### ISSUE TITLE
export issues

### ISSUE THREAD

**Issue by therealrooster** [wiglenet/wigle-wifi-wardriving#483]
Phone: Pixel 4XL
Android Version: 11

When attempting to either export a CSV/KML run or CSV/KML DB, the user has no option to save the export to local or external storage.  Only "Share" is presented and "sharing" the export is limited to a small group of apps.  

Not sure if this is intended behavior, but to me it wouldn't make much sense to offer an export feature.. then require the user to have to move the export through some other App just to get to the data??

**Comment by bobzilladev** [comment]
Unfortunately android 10 and later no longer gives access to write to the pseudo sdcard, so we've had to change how the app works.

**Comment by therealrooster** [comment]
So is there a way that I'm missing, to get the CSV export directly to internal storage?

**Comment by bobzilladev** [comment]
You can share to another app that advertises the capability, but it would likely have to write into its own storage area. You can write media files into a system area, but csv/kml/sqlite don't fit that bill. So haven't found a good way to do the old style of just write to /sdcard/wiglewifi like we used to.

**Comment by therealrooster** [comment]
Well that's a bummer, but thank you for your efforts with the app and your quick response!!
