### ISSUE TITLE
GPS not detected from wigle 

### ISSUE THREAD

**Issue by Villelmo** [wiglenet/wigle-wifi-wardriving#484]
### Pre-submission checklist

- [X] I am submitting a bug report, not a feature request.
- [X] I am running the latest version of wigle-wifi-wardriving.
- [ ] I have have searched for similar issues, but did not find any matches.

### Description

I trying scan any network from wigle but the GPS not detected. 

### Steps to reproduce

1.Go to wigle-wifi-wardriving
2.Set up WIFI-GPS-Bluetooth 
3.Scan networks 
4.Upload to wigle.net (empty file)

### Screenshots
![Screenshot_2021-03-27-11-51-37](https://user-images.githubusercontent.com/7723227/112729717-3443fc80-8ef3-11eb-8e40-37dad4ab3fe7.png)

### System information

-Phone: [Samsung Galaxy S4 mini SCH-i435]
-Phone Operating System: [Android 4.4.2]
-App version: [2.51]

**Comment by rksh** [comment]
A few questions to confirm before trying to diagnose:
- OS Release (is this Samsung stock or Lineage/some other variant?)
- WiGLE release (FOSS or mainline?)
- Installation channel (F-Droid, Play store, other?)
- Does the device GPS work in other contexts?
- Can you confirm GPS access in the system application settings?

**Comment by rksh** [comment]
closing after 5 months of inactivity. upon launch, the application should request FINE + COARSE grained location - if the permission is not granted, this would lead to the illustrated case, but we don't have testing data or further detail to work with.
