### ISSUE TITLE
The map is not displayed on the screen

### ISSUE THREAD

**Issue by CESARKHALID** [wiglenet/wigle-wifi-wardriving#489]
The map is not displayed on the screen 
![map not displayed on screen](https://user-images.githubusercontent.com/73532128/124723402-efbcf980-df02-11eb-977e-2568da8218b5.png)

**Comment by CESARKHALID** [comment]
hi owner of this app please u can resolve this one how i can show and display it

**Comment by bobzilladev** [comment]
You can try pinching to zoom in and out, that may get the google map view to initiate a new render. If nothing happens then likely the device needs to have Google Play Services installed, which is required for google maps to work in android.

**Comment by CESARKHALID** [comment]
i hv huawei device !

**Comment by rksh** [comment]
Is this a local build from the repository? If so, you will need to update the AndroidManifest file with your own (free) API key.
If Hauwei's proprietary changes have disabled Google maps, I'm not sure where we can go from there.
