### ISSUE TITLE
Feature request: Monthly leaderboard

### ISSUE THREAD

**Issue by lozaning** [wiglenet/wigle-wifi-wardriving#495]
Would be great if there was a viewable monthly leaderboard, like the one that already exists for lifetime score. Could be fun and add a bit more to the month to month competitiveness to be able to see which users are above/below you and by how much, for the current month.

**Comment by rksh** [comment]
vs. just clicking the monthly headers to sort in the existing leaderboard?

**Comment by lozaning** [comment]
Wow, today years old when I learned those column headers are sortable.
