### ISSUE TITLE
Run and Total Distance are off by a lot

### ISSUE THREAD

**Issue by signout** [wiglenet/wigle-wifi-wardriving#496]
On my Nokia 8.1 the travelled distance seems to be wildly exaggerated. See the attached picture. I’m sure you can see that if I were doing that speed in an urban environment I would probably have been pulled over. 
![303279E6-CDF8-4BF5-9F44-1B9FB198E2E4](https://user-images.githubusercontent.com/678480/131745903-a3947521-0aae-4a6c-a2e8-5269cf4ac8da.jpeg)

**Comment by Theintrepid1** [comment]
Also having this issue. Doesn't seem to happen every time.
![Screenshot_20210908-150517_WiGLE_WiFi_Wardriving](https://user-images.githubusercontent.com/90929767/133836285-cefc2fd0-f94f-4774-b1a4-0c511eeb3fbc.png)

**Comment by signout** [comment]
As far as I can see this is periodic, and often occurs when there is Beidou signal. I'll try to notice if that's always the case or if it might glonass or galileo as well.

**Comment by rksh** [comment]
if you could turn on "display route for run," you'll probably see some interesting behavior as well (big "jags" in the route lines).
We've tried to get fixes working for this before, but ended up disabling them because the cure is sometimes worse than the disease:
https://github.com/wiglenet/wigle-wifi-wardriving/blob/master/wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/listener/GPSListener.java#L495

**Comment by rksh** [comment]
Note: GPS fidelity gets particularly bad in proximity to very tall skyscrapers (see web maps for distortion around Willis tower, Burj Khalifa, 1 World Trade Ctr.!)

**Comment by rksh** [comment]
here's a PR that'll help debug this by allowing you to view your routes, if you elect to log routes!
https://github.com/wiglenet/wigle-wifi-wardriving/pull/502

**Comment by pejacoby** [comment]
Seeing the same issue on a Galaxy S9 (SM-G960U) running Android 10, One UI v2.5, Kernel 4.9.186-2290479, Build number QP1A.190711.020.G960USQU9FVB2.

Comparing to a Galaxy S7 (running Android 8), the Run Distance shown on the S9 can be 3 to 4 or more times as far on the same run.  When tracking routes, the GPX files created show ACCURATE distance, matching the S7 within a few tenths or a mile or less.  The GPX file distance is the same in the app, as well as when loading the GPX file into another app.

GPS settings in the Wigle app (v2.67) are the same
 - Use Network Location Provider
 - Time between GPS update: 250ms
 - GPS Timeout: 30 sec
 - Network Location Timeout: 1 min

Test drives have been out in the wide open freeways, no downtowns or tall buildings.  Screencaps and GPX files available upon request.

**Comment by rksh** [comment]
https://github.com/wiglenet/wigle-wifi-wardriving/pull/545
ok - distance will match route now!
Unfortunately, we can't go back and fix your total distance, but this will get future distances right!
