### ISSUE TITLE
Ask me do I want to turn WiFi off before you do it.

### ISSUE THREAD

**Issue by Mikaela** [wiglenet/wigle-wifi-wardriving#5]
1. I turn Wigle on and go somewhere.
2. I arrive at somewhere and quit Wigle and turn off WLAN.
3. I I start Wigle and return home.
4. I upload information to Wigle.net and quit it.
5. Wigle turns off WiFi without asking me and I must enable it by hand.

**Comment by kuraz758** [comment]
I have a similar problem, but exiting the wigle app doesn't seem to solve it, Wi-Fi keeps getting turned off when I turn it on. Uninstalling helped,  but that's unacceptable.

**Comment by Raffaele74** [comment]
Id like If i can set a calendar on/off.
So I can say app: work when .... (not office, not in the night) and I'm sure it set wifi on off.
Also if I can set off WiGLE when I'm stuck, this helps me to have WiGLE always on.

**Comment by Raffaele74** [comment]
If it remember me about wifi, it might even remind me to turn off the GPS.

**Comment by rksh** [comment]
re: this issue - we've avoided releasing only because stalling shutdown while waiting for an answer has some negative consequences (the app keeps using power until you agree, violates least-surprise). How would folks feel about a preference setting for a start, eventually maybe adding geofencing?

**Comment by rksh** [comment]
sadly in android Q, applications won't be able to perform this operation any longer. closing the issue since it's going to be beyond our control. see [android developer notes](https://developer.android.com/preview/privacy/camera-connectivity#restriction-enable-disable-wifi)
