### ISSUE TITLE
Typo in Polish - Turn on the toast

### ISSUE THREAD

**Issue by olekstomek** [wiglenet/wigle-wifi-wardriving#501]
This is just a simple typo, and it's understandable. However, maybe someone will correct it by the way: now it is "W**t**łącz", it should be "Włącz", without "t". 
![1632077246390](https://user-images.githubusercontent.com/26818304/133939298-31d9dcab-31ef-4276-9663-1d05079011ae.jpg)

**Comment by bobzilladev** [comment]
Updated it to "Wyłączyć" since it's supposed to be "disable" or "turn off", and it looks like from google translate that it was the opposite before.
https://github.com/wiglenet/wigle-wifi-wardriving/blob/master/wiglewifiwardriving/src/main/res/values-pl-rPL/strings.xml#L257

**Comment by olekstomek** [comment]
Ah OK, I understand (it actually makes sense and probably the error was created because the letter "Y" is near to the letter "T" in the qwerty keyboard). :)
Now it's understandable, but it's more natural to "Wyłącz". "Wyłączyć" it is the infinitive. The rest of the menu options are not written in the infinitive so it sounds better "Wyłącz".

**Comment by bobzilladev** [comment]
Ah, ok, switched it to that: https://github.com/wiglenet/wigle-wifi-wardriving/commit/a217ee63e7ffa594410df775b7ac23efe07e1a1a
Thanks!

**Comment by olekstomek** [comment]
Perfect! Thanks you too!
