### ISSUE TITLE
Bluetooth devices seen not clearing

### ISSUE THREAD

**Issue by Firecul** [wiglenet/wigle-wifi-wardriving#506]
With current networks only set to on it seems Bluetooth devices don't respect it, the list can get extremely long in a short amount of time as a result.

-------
![](https://i.imgur.com/KFni6tu.png)
-------
![](https://i.imgur.com/vtn1uQA.png)

**Comment by rksh** [comment]
is the issue that the list og BT devices displayed there should no longer be visible? BT nets certainly leave the display regularly when out of range. Please include steps to reproduce the issue in detail.

**Comment by Firecul** [comment]
Yes, I started the application while at home and many of these devices are visible from there. After driving to my destination many miles away, the devices which can't possibly still be being picked up are still showing up in the list. 

I'll be honest not sure how else to reproduce, I started the app, minimised it, drove somewhere else and opened the app to look at it and the devices were still there. Clicking on some of them at random shows the app hasn't seen them for hours in cases.

This bug doesn't happen every time but maybe 20% of the time for me.

**Comment by rksh** [comment]
Here's hoping we have a reliable fix for this in the next release.

**Comment by rksh** [comment]
request a retest with version 2.71, now in beta channel and rolling into production

**Comment by Firecul** [comment]
> request a retest with version 2.71, now in beta channel and rolling into production

I'll keep an eye out for it happening, or not, then 👍

**Comment by Firecul** [comment]
So far I have not seen this happening while running 2.71

**Comment by Firecul** [comment]
Yeah I haven't seen it for a while now and I'm now on 2.73, so I'd say it fixed. Thanks guys.
