### ISSUE TITLE
Wrong position of WiFi networks

### ISSUE THREAD

**Issue by florian-184-de** [wiglenet/wigle-wifi-wardriving#53]
Network position is often very wrong.
What about a function to only use a good GPS signal?
I was on Tenerife and not anywhere in the desert.
Example: https://www.dropbox.com/s/s4x54wtr61wdd6y/Screenshot_2015-08-06-12-45-05.png?dl=0

**Comment by bobzilladev** [comment]
Server side we do a lot of filtering, using what the gps reports for accuracy, along with a bunch of other factors. In the app it will move the mapped location to the strongest signal, but we could probably blend that with reported accuracy in the case that the strongest signal came in while the gps was way off base. The accuracy often lies in these devices though, saying it's +/- tens of meters when it's really kilometers.
