### ISSUE TITLE
Towers don't show up anymore

### ISSUE THREAD

**Issue by rimwulf** [wiglenet/wigle-wifi-wardriving#532]
I am no longer seeing cell towers showing up even when connected to only a cell tower and the CELL box is indeed checked. I tried my Moto G power (2020) Android 10 and my Galaxy s22.

**Comment by rksh** [comment]
have you checked your display filters? (the wrench icon on the main list)

**Comment by rksh** [comment]
It's also worth checking app permissions in case anything's been automatically removed by the system.

**Comment by rimwulf** [comment]
I uninstalled and reinstalled it and it seems to be working it still
doesn't show up in the counter but I don't know if it has to do with the
fact that I've already recorded previously before it. I'm pretty really
sure that it could be user error. I gave it the phone permission. I'm using
in on Android 10,11 and 12

**Comment by rksh** [comment]
The green, red, and blue "counters" at the top of the list and map screens are "new" - if you have already observed the towers previously, they don't increment.

**Comment by rksh** [comment]
without further clarification, we'll be closing this issue

**Comment by rimwulf** [comment]
It's an old one anyway. Ended up uninstalling and reinstalling it anyway,
that fixed it.

**Comment by rksh** [comment]
thanks - bug reports always appreciated.
