### ISSUE TITLE
Add support for GNSS full tracking

### ISSUE THREAD

**Issue by devicenull** [wiglenet/wigle-wifi-wardriving#533]
https://barbeau.medium.com/gnss-interrupted-the-hidden-android-setting-you-need-to-know-d812d28a3821
https://developer.android.com/reference/android/location/GnssMeasurementRequest.Builder#setFullTracking(boolean)

An option for enabling "full tracking" would be nice to have -  even better if it could be enabled only when the phone is plugged in!

**Comment by itissid** [comment]
Interesting reads. But I would imaging that turning on full measurement would also be useful when someone has turned on scanning and the battery level is >= X% and not just while plugged in.

**Comment by bobzilladev** [comment]
Will be in next release, user-beware as far as battery life: https://github.com/wiglenet/wigle-wifi-wardriving/pull/633
