### ISSUE TITLE
Android 13: App crashes after for grounding and then uploading 

### ISSUE THREAD

**Issue by lozaning** [wiglenet/wigle-wifi-wardriving#535]
Somewhat reliably now I can can get the app to through the following steps.

# Open the app and start a run
# phone falls asleep
# some time (an hour at least?) passes
# wake up phone
# open wigle app
# tap upload button
# see app crash

Phone: Pixel 6 pro
OS: Android 13

When I open the app back up and tap upload it looks like uploads the previous run just fine. So no data loss is happening, just a fault and I have to re&open the app.

I can try to grab ADB logs after my next run if I think to plug my phone in before trying to upload. The built in error reporting doesn't seem to be working for me, and just generates an empty report.

**Comment by rksh** [comment]
requesting a retest with 2.71 now in the beta channel!

**Comment by rksh** [comment]
sounds like we've solved this one.
