### ISSUE TITLE
Dashboard Run Duration/Scan times display & increment oddly on Android 8.0

### ISSUE THREAD

**Issue by pejacoby** [wiglenet/wigle-wifi-wardriving#540]
Wigle WiFi 2.65 beta
Samsung Galaxy S7 Edge (SM-G935V)
Android 8.0.0, Samsung experience 9.0, Kernel 3.18.71

In the Dashboard page, the Run Duration and Scan Duration time values are display quite strangely.  I attach two screen shots, one after a long run and another less than a few minutes after starting Wigle.

Time incrementing goes like this:
00:02 through 00:59, then 01:60, 01:61, 01:62.... 01:99, then 01:100, 01:101, 01:102, ....

After a multi-hour run, the time showed 2:178:10714
![S7Edge-WIgle236-Dashboard-few minutes in](https://user-images.githubusercontent.com/16978661/194647128-7ad5b62b-d54a-41d9-be82-96997528cd77.jpg)
![S7Edge-WIgle236-Dashboard-Long Run](https://user-images.githubusercontent.com/16978661/194647135-73bcdddd-2f8d-4b75-9f45-c2163dc81713.jpg)

**Comment by pejacoby** [comment]
FYI also seen on Galaxy S9 with Android 10.

**Comment by bobzilladev** [comment]
Was the result of a contributed change, we'll revert that.

**Comment by bobzilladev** [comment]
Fixed in 2.66, rolling out now. https://github.com/wiglenet/wigle-wifi-wardriving/commit/73f84b8b75320a835d531f4cb870c7fc94db780f

**Comment by bobzilladev** [comment]
Thanks for the bug report, by the way :)
