### ISSUE TITLE
[Feature request] client side trilateration

### ISSUE THREAD

**Issue by Kiskadee-dev** [wiglenet/wigle-wifi-wardriving#544]
Most devices today are powerfull enough to handle this, but it should be optional and the user should be able to choose which networks they want to process (so they doesn't end processing thousands of networks while walking in the street)

Great for areas where phone signal is bad/non-existant and you can't rely on the internet for an extended amount of time (yes, it happens)

Currently the app will log many points and plot a red circle that seems to have a random behaviour as it often plots the circle away from a good cluster

**Comment by rksh** [comment]
it's in there!
https://github.com/wiglenet/wigle-wifi-wardriving/blob/master/wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java#L327

**Comment by rksh** [comment]
absent further clarification, closing as "already implemented"

**Comment by Kiskadee-dev** [comment]
@rksh Its definetelly not implemented, the current behaviour (even in the current version) is for the circle to show up where the device first seen the network in the new session or the last one if its not currently visible, it doesn't do any kind of trilateration, and thus, when you boot the app and look at the list you'll see many networks with the circle in the same exact position, and if it sees the network with an innacurate gps lock it will show the circle at the center of that innacurate position.

I've tried looking into the data it saves in the db to do my own service but couldn't export the whole history either, it seems to export a very slim db with only the latest and "better position" (position where the signal was strongest) of the networks, but if the gps was bad then we can't really rely on it.

Sorry for the huge delay, if you need further clarifications hit me up!

**Comment by rksh** [comment]
https://github.com/wiglenet/wigle-wifi-wardriving/blob/eede48cdd589e7f62d1870ea65f83275b6eee471/wiglewifiwardriving/src/main/java/net/wigle/wigleandroid/NetworkActivity.java#L352

I'm afraid you're going to have to be a lot more specific about what you're expecting. Please include the activity in which you expect to see this information, how it will be manifest, and what the intended application is.

**Comment by Kiskadee-dev** [comment]
@rksh Here's a image of the issue, i've rebooted the phone and faked the gps location, in the app the red circle is the same for all networks besides the observations, so the trilateration, if present, isn't really used in the app.

![WiGLE WiFi Wardriving](https://github.com/user-attachments/assets/d2ea559b-8aad-4b26-9fda-3bdb18dd5ac1)

**Comment by rksh** [comment]
Pull requests are welcome. Feature request remains closed.
