### ISSUE TITLE
WPA3 network is incorrectly logged as WPA2

### ISSUE THREAD

**Issue by huaracheguarache** [wiglenet/wigle-wifi-wardriving#546]
Hi

I've tried using my old Nokia 8.1 for wardriving, and I've noticed that my own WPA3 network for some reason gets incorrectly logged as a WPA2 network. When I export my database file I can see that my network is logged with the following security:

`[RSN-SAE+FT/SAE-CCMP][ESS]`

It could be that the issue is caused by my network having WPA3 enabled together with 802.11r.

**Comment by huaracheguarache** [comment]
The WiFi symbol in the app correctly shows WPA3 as the security level of the network, but it's incorrectly listed as WPA2 after uploading it to the Wigle website. I assume that this is an issue with the backend processing of uploaded database files on Wigle. This could potentially lead to significant undercounting of WPA3 networks.

**Comment by bobzilladev** [comment]
Right you are! Server side will now recognizing SAE and EAP_SUITE_B_192 as WPA3 capabilities, like the client does. Thanks for the bug report!
