### ISSUE TITLE
Invisile router manufacturer for TP-Link TL-MR3420 v5.1 and Xiaomi Mi Wi-Fi Range Extender Pro

### ISSUE THREAD

**Issue by olekstomek** [wiglenet/wigle-wifi-wardriving#548]
There is no BSSID (`6aff7b`) for TP-Link TL-MR3420 v5.1 and no BSSID (`64644a`) for  Xiaomi Mi Wi-Fi Range Extender Pro - these devices are not recognized:
![image](https://user-images.githubusercontent.com/26818304/204159606-d044a9e0-94d2-447d-87a7-d4bb76e1f308.png)
Is there a public database with updated values for devices? Because this is just an example and I had the same problem once before on a device other than mine.
More details [here](https://forum.openwrt.org/t/vendor-name-of-router-is-hidden-in-some-openwrt-versions/143939).

The same I described here: https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/394

**Comment by bobzilladev** [comment]
Those are mappings of the BSSID (MAC) prefixes to the company that owns the range, it's about time we updated that local copy, will get that in the next release.

**Comment by bobzilladev** [comment]
Looks like the first one isn't in the datasets, but the latter one is. Updated in https://github.com/wiglenet/wigle-wifi-wardriving/commit/99fae48a515c2d43f9027dbb1562fa17e00ece07

**Comment by olekstomek** [comment]
> but the latter one is

yes
`64:64:4A	BeijingX	Beijing Xiaomi Mobile Software Co., Ltd`
but why it wasn't mapped (empty value) as you can see above?

>  Updated

Thanks!
