### ISSUE TITLE
Osm tiles

### ISSUE THREAD

**Issue by pschonmann** [wiglenet/wigle-wifi-wardriving#56]
When osm tiles checked, i still getting google. Even if i restart app. Title od map panel is still named as openstreetmap / checked or unchecked

**Comment by bobzilladev** [comment]
The app switched to Google maps in version 2.5, which is used exclusively. Thanks for the note, we'll remove that checkbox in a future version.

**Comment by bobzilladev** [comment]
This commit removes the now-useless osm checkbox.
https://github.com/wiglenet/wigle-wifi-wardriving/commit/0d673629b3faf8f1dfc4cf32161df6d0a9e33180
