### ISSUE TITLE
offline maps support

### ISSUE THREAD

**Issue by pschonmann** [wiglenet/wigle-wifi-wardriving#57]
Hi, its pain in ass to download map tiles. Its drain my data. Fup 200Mb here.
Should ve posible add support for mapsforge? 
Im using map tiles in other apps. For geocaching, Locus etc. One file and if you want, render rules for customizing.

**Comment by bobzilladev** [comment]
We used to use osmdroid, but we were asked by them to run our own tileserver, which we did set up but let it atrophy. We moved back to google maps for more features and a nice clustering library. I toyed with trying to make it configurable between good/osm, but ran into issues with goog maps object hierarchy making it not work. Then we did a huge move to new infrastructure and dropped the osm tileserver entirely. So it's unlikely we'll go back to osm anytime soon.

**Comment by pschonmann** [comment]
I think that project https://github.com/mapsforge/mapsforge/ . You dont need own server. All data stored in one file on my phone and rendered by phone too

**Comment by twzkxkan** [comment]
@bobzilladev Would you consider using the [Mapbox API](https://www.mapbox.com/blog/mapbox-mobile-android/) as a an alternative for Google maps?

**Comment by bobzilladev** [comment]
@twzkxkan Coming soon: Point clustering
Would need that at a minimum, we display thousands of data points. And it's hard to compete with google's free pricing (at our scale).
The clustering lib (somewhat abandoned by goog at this point): https://github.com/googlemaps/android-maps-utils

**Comment by twzkxkan** [comment]
>Would need that at a minimum

Ah, I see. I appreciate you giving it a look.
