### ISSUE TITLE
Current networks missing

### ISSUE THREAD

**Issue by melbournefan** [wiglenet/wigle-wifi-wardriving#578]
After I switched on my WiFi Hotspot, the list of current networks has seemed to have disappeared from the home screen, there also seems to be some text formatting issue around how many networks were received in "0 ms". I've attached the screenshot below which should help.

Currently running MIUI 14.0.4 which is based off Android 13

Thanks

![Screenshot_2023-03-30-21-32-38-142_net.wigle.wigleandroid.jpg](https://user-images.githubusercontent.com/41057813/228809903-66e6ccf0-7e3f-4710-bf3f-4166708a8149.jpg)

**Comment by melbournefan** [comment]
Oops, yeah it was paused at the time however it used to show current networks while paused, that said it's still blank even when scanning

 tol![Screenshot_2023-03-31-13-25-18-700_net.wigle.wigleandroid.jpg](https://user-images.githubusercontent.com/41057813/229007131-3bc22f36-d828-4d0d-8c7c-e528057c8646.jpg)

**Comment by rksh** [comment]
Please specify:
1. whether the behavior changes when you disable the portable hotspot
2. what version of the app you're using
3. how you installed it
4. whether you have any active filters set up in the application (the "wrench" icon in the screen above.)

**Comment by melbournefan** [comment]
Hi, 

App version was 2.71
I downloaded the app from Google Play
The networks were still missing even after I turned off the hotspot and it appears that I had a random BSSID in the filtering section of the app (where the wrench is) so removing that fixed the issues

Thanks
