### ISSUE TITLE
Filter for own mobile hotspot

### ISSUE THREAD

**Issue by TLBM** [wiglenet/wigle-wifi-wardriving#58]
Hi!

Mobile personal hotspots aren't really helpful for building a geolocation-map as they move with the user. 
So it would be really nice if one could filter out his/her own ones to make the map more accurate and keep the "data pollution" down.
Or are there algorithms serverside to detect this?

**Comment by strasharo** [comment]
Yup, one vote from me as well. It would be nice if we're able to remove any entries, that we consider to be not very useful to the database, prior submitting our observations to Wigle.

**Comment by bobzilladev** [comment]
Not a bad idea.

**Comment by rksh** [comment]
This has been implemented with the new filter dialog - feedback welcome!
