### ISSUE TITLE
[BUG] Inconsistent page loading on rankings activity

### ISSUE THREAD

**Issue by rksh** [wiglenet/wigle-wifi-wardriving#582]
Based on 
[this report from the forums](https://wigle.net/phpbb/viewtopic.php?p=11623&sid=b8a73004fe98b06dd8bc3dd58ca1c106#p11623), it seems likely there's an error in the pagination logic. Seeking additional testing and answers to these questions:
- does this happen consistently on load, or only after scrolling/loading more?
- if you scroll to the top and swipe down to refresh, does it that fix/change things?
- What's displayed when you first launch the activity?
- when you re-start the activity (go back to the main screen, then return), does that fix or change things?

**Comment by rksh** [comment]
fix in https://github.com/wiglenet/wigle-wifi-wardriving/pull/583

**Comment by rksh** [comment]
requesting retest with 2.72

**Comment by rksh** [comment]
still broken in 2.73.

**Comment by hsiboy** [comment]
Confirmed fixed 👌

Thank you.

**Comment by rksh** [comment]
it was a dumb mistake on my part - thanks for the help in catching it!
