### ISSUE TITLE
Proprietary dependencies

### ISSUE THREAD

**Issue by dafotrno** [wiglenet/wigle-wifi-wardriving#60]
https://f-droid.org/forums/topic/wigle-outdated/

Can this dependency be dropped; alternately can a version without it be made available? I'd really prefer to keep using the app and I assume that the thousands of others who get it through F-Droid agree.

**Comment by bobzilladev** [comment]
Google Play Services are available to non-official android devices, you don't need the Google Play Store to install them. We realize Google Play Services is not open source, but we are not zealots about such things. It would be a maintenance headache to have versions with and without mapping, there are a lot of integration points and Google Maps just works better than alternatives (we used to use OSMDroid).

As you know, Wigle Wifi Wardriving is open source, I suppose you could start a fork project to maintain a non-mapping version if you are up to the task.
