### ISSUE TITLE
Send broadtcast on sucessful upload

### ISSUE THREAD

**Issue by grim0us** [wiglenet/wigle-wifi-wardriving#683]
It would be great to know when an upload has finished successfully. Would it be possible to create a broadcast to notify other apps, e.g. Tasker, when a successful upload has been completed?

[Tasker intents](https://tasker.joaoapps.com/userguide/en/intents.html) under "Receiving Intents"

**Comment by rksh** [comment]
will be included in https://github.com/wiglenet/wigle-wifi-wardriving/releases/tag/2.86 and up
