### ISSUE TITLE
[BUG] Again the app's layout shows arrows from the drop-down menu in the navigation menu as you scroll

### ISSUE THREAD

**Issue by olekstomek** [wiglenet/wigle-wifi-wardriving#689]
It is the same again as I described here https://github.com/wiglenet/wigle-wifi-wardriving/issues/519 because:
https://github.com/wiglenet/wigle-wifi-wardriving/commit/15fe450b3f063bc66a4015f8898582796f7f87e1#diff-c066de3914a8b40818307a33cbc46870a02432fa23eda02f93d403a65984cd2cL6

**Comment by rksh** [comment]
fix merged, will be in https://github.com/wiglenet/wigle-wifi-wardriving/releases/tag/2.86. Comment added to prevent regression in the future (this weird fix was flagged as a correctness issue by the compiler). Thanks for the good catch!

**Comment by olekstomek** [comment]
That's great, thanks!
