### ISSUE TITLE
When sim in a dual sim phone is disabled the disabled: sim's home network always appears as a -98dB signal

### ISSUE THREAD

**Issue by nathanielcwm** [wiglenet/wigle-wifi-wardriving#698]
Android 14, Samsung SM-S901E (S22)

Re-enabling the sim card fixes the phantom cell tower issue.

![Screenshot_20240407_150001_WiGLE WiFi Wardriving.png](https://github.com/wiglenet/wigle-wifi-wardriving/assets/22572406/897d9071-fece-40f4-abed-ea39b614e0b8)

**Comment by nathanielcwm** [comment]
Or it might be stuck on the last cell tower that it was connected to?

**Comment by bobzilladev** [comment]
That is what android is reporting to the application. If you like we can remove that network from the dataset.

**Comment by nathanielcwm** [comment]
It's kinda interesting that it's reporting a phantom cell tower rather than reporting nothing though. Or is this expected behaviour?

**Comment by nathanielcwm** [comment]
Seems to be a device specific limitation.
