### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by bellingeri** [wiglenet/wigle-wifi-wardriving#70]
Hello.

After working at the Italian translation (revised and completed) I tried to send it to the email WiGLE-admin[at]WiGLE.net - as indicated on the site - a month ago.

I fear it is not arrived... I try to attach it here: [strings.zip](https://github.com/wiglenet/wigle-wifi-wardriving/files/333014/strings.zip)

I hope it is useful.
Thanks for your work

**Comment by bobzilladev** [comment]
We received it, there just hasn't been a release since then. Thanks for your efforts!
