### ISSUE TITLE
HTML and linebreak translation in news view doesn't work.

### ISSUE THREAD

**Issue by kill0rz** [wiglenet/wigle-wifi-wardriving#78]
In news view, HTML and linebreaks (\n) aren't translated so these codes are shown as plain text.

![pic1](http://fs5.directupload.net/images/160802/92msl8zx.png)
![pic1](http://fs5.directupload.net/images/160802/xsbdwnea.png)

**Comment by bobzilladev** [comment]
aye, didn't get around to that before self-imposed deadline.
