### ISSUE TITLE
Second line of text on network list and uploads is black on N Developer Preview 5

### ISSUE THREAD

**Issue by tgies** [wiglenet/wigle-wifi-wardriving#80]
![screenshot_20160813-135519](https://cloud.githubusercontent.com/assets/1594352/17645133/1013c836-6162-11e6-9495-39f294011dc8.png)
![screenshot_20160813-135508](https://cloud.githubusercontent.com/assets/1594352/17645135/17a31836-6162-11e6-9b1a-f731b1d63157.png)

This text is supposed to be the same light gray color seen throughout the app. I think this is a new Support Library bug on N as I have seen a similar problem with other apps.

This is on a Nexus 6 running build NPD90G.

**Comment by bobzilladev** [comment]
That is an odd one, we don't set any kind of color on those textviews.

**Comment by tgies** [comment]
I think that's why it's happening. It seems there's some problem now where
textviews in fragments are not inheriting the correct dark style under
certain circumstances. Sync for Reddit is exhibiting what looks like the
same problem with some of its modal dialog fragments when the support
library dark theme stuff is used.

It might be worth explicitly setting a style on this text as a workaround,
the same problem is likely to exist on the release version of N. I couldn't
find an Android bug filed for it.

**Comment by tgies** [comment]
Looks like this was fixed a few releases ago, thanks!
