### ISSUE TITLE
Stopping tts can take very long

### ISSUE THREAD

**Issue by kuraz758** [wiglenet/wigle-wifi-wardriving#81]
It have tts setup to only say the ssids. But when there are many of them it takes a while to say them all. When I use the ... Menu to silence the app it wants to finish saying all ssids it hasn't told me about yet. When I exit the app it stops immediately but in my case I would have to first silence it then exit then restart the app.

**Comment by rksh** [comment]
fix will be in  v2.61

**Comment by bobzilladev** [comment]
Was fixed back then: https://github.com/wiglenet/wigle-wifi-wardriving/commit/619dc98a2c2815d2620e362d921e4660fc280217
