### ISSUE TITLE
Mute Audio

### ISSUE THREAD

**Issue by sameribr** [wiglenet/wigle-wifi-wardriving#87]
I have been searching in the source code for the default of "Mute Audio" as the app play audio and tts by default. Could someone point me where is set by default to turn it off in a built which does not set audio and speech to be turned on by default?

**Comment by bobzilladev** [comment]
The main list view has a 'Mute' in the 3 vertical dots menu. That is permanently saved in preferences, so it will stay muted until you unmute it using the same menu item.
