### ISSUE TITLE
Store distance stats in /mnt/sdcard/wiglewifi

### ISSUE THREAD

**Issue by RicoElectrico** [wiglenet/wigle-wifi-wardriving#9]
When I rooted my phone and installed Wigle Wifi again on a clean system, I noticed that distance stats are gone. I think it is a good idea to move them to the memory card.

**Comment by rksh** [comment]
note that the GPX export feature in 2.49 provides the ability to visualize export route "traces" - we need a "route list" interface before you'll be able to retrieve old runs, but we're working on it!

**Comment by rksh** [comment]
also worth noting that direct access to ALL filesystem elements is being rapidly deprecated through the Android 10/11 product cycle -we're helping out by providing access via "intents" in the short term, but figuring out automated sync/sharing of data on a per-user basis will become increasingly important.

**Comment by rksh** [comment]
with recent PRs + enabling GPX-logging, per-run distance statistics will be present in exportable GPX files in the next release. Unfortunately, the other element of this issue (/mnt/sd/... access) will be permanently disabled when we switch to SDK 31. Closing this issue as the GPX export is as close to a resolution under the new system as we're liable to get.
