### ISSUE TITLE
idea on better updating location of ssid

### ISSUE THREAD

**Issue by FunGuy7474** [wiglenet/wigle-wifi-wardriving#99]
When some one goes past a area and they get the first (ssid/mac address) and it puts it in the database but when they go to another street and they find that same ssid but it is stronger signal at the new location it will update the location and also update how strong the signal on the database automatically. That will help pinpoint where that ssid is located at. 

Also a feature on a radar style of map using the best location with the strongest signal going from the database of all of the driving around the area.

**Comment by bobzilladev** [comment]
That's how it works, it keeps track of the best signal seen and uses that as the location shown in the app. All observations are sent back to the server for analysis.

**Comment by FunGuy7474** [comment]
it do not update the location when it gets a stronger signal from the tests i been doing so far.
